services:
  db:
    container_name: converter-db
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
  audio-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-converter
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run db-sync && npm run dev"